"""
Multi-Query Retriever
=====================

The Multi-Query Retriever addresses the limitation of single-query retrievers by
automatically generating multiple related queries from the original query. This helps
capture documents that might be relevant but wouldn't be found with just one query.

Key Benefits:
- Improves recall by generating alternative phrasings
- Handles ambiguous queries better
- Reduces the impact of query formulation on retrieval quality
- Leverages LLM's understanding to create diverse queries

How it works:
1. Takes the original user query
2. Uses an LLM to generate multiple related queries
3. Performs retrieval for each generated query
4. Combines and deduplicates results
5. Returns the merged result set
"""

from langchain.retrievers import MultiQueryRetriever
from langchain.vectorstores import FAISS
from langchain.embeddings import OpenAIEmbeddings
from langchain.llms import OpenAI
from langchain.docstore.document import Document
from langchain.text_splitter import CharacterTextSplitter
from langchain.prompts import PromptTemplate
from typing import List, Set
import logging

# Set up logging to see generated queries
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class CustomMultiQueryRetriever:
    def __init__(self, llm=None, embedding_model=None):
        """
        Initialize the multi-query retriever.
        
        Args:
            llm: Language model for query generation
            embedding_model: Embedding model for vector search
        """
        self.llm = llm or OpenAI(temperature=0.7)
        self.embedding_model = embedding_model or OpenAIEmbeddings()
        self.vector_store = None
        self.base_retriever = None
        self.multi_query_retriever = None
        
    def create_vector_store(self, documents: List[str]):
        """
        Create vector store from documents.
        
        Args:
            documents: List of document texts
        """
        # Create Document objects
        docs = [Document(page_content=doc) for doc in documents]
        
        # Create vector store
        self.vector_store = FAISS.from_documents(docs, self.embedding_model)
        
        # Create base retriever
        self.base_retriever = self.vector_store.as_retriever(
            search_kwargs={"k": 3}
        )
        
        # Create multi-query retriever
        self.multi_query_retriever = MultiQueryRetriever.from_llm(
            retriever=self.base_retriever,
            llm=self.llm
        )
    
    def retrieve(self, query: str) -> List[Document]:
        """
        Retrieve documents using multi-query approach.
        
        Args:
            query: Original user query
            
        Returns:
            List of relevant documents
        """
        if not self.multi_query_retriever:
            raise ValueError("Vector store not created. Call create_vector_store() first.")
            
        return self.multi_query_retriever.get_relevant_documents(query)
    
    def get_generated_queries(self, query: str) -> List[str]:
        """
        Get the queries generated by the LLM.
        
        Args:
            query: Original query
            
        Returns:
            List of generated queries
        """
        # Custom prompt for query generation
        prompt = PromptTemplate(
            input_variables=["question"],
            template="""You are an AI assistant that generates multiple search queries.
            Generate 3 different search queries that would help find information related to: {question}
            
            Make the queries diverse and capture different aspects of the original question.
            
            Queries:
            1."""
        )
        
        # Generate queries
        response = self.llm(prompt.format(question=query))
        
        # Parse the response to extract queries
        lines = response.strip().split('\n')
        queries = []
        for line in lines:
            if line.strip() and (line.strip().startswith('1.') or 
                                line.strip().startswith('2.') or 
                                line.strip().startswith('3.')):
                query_text = line.strip()[2:].strip()
                if query_text:
                    queries.append(query_text)
        
        return queries

class AdvancedMultiQueryRetriever:
    """
    Advanced multi-query retriever with custom query generation strategies.
    """
    
    def __init__(self, llm=None, embedding_model=None):
        self.llm = llm or OpenAI(temperature=0.7)
        self.embedding_model = embedding_model or OpenAIEmbeddings()
        self.vector_store = None
        
    def create_vector_store(self, documents: List[str]):
        """Create vector store from documents."""
        docs = [Document(page_content=doc) for doc in documents]
        self.vector_store = FAISS.from_documents(docs, self.embedding_model)
    
    def generate_queries_by_perspective(self, query: str, num_queries: int = 3) -> List[str]:
        """
        Generate queries from different perspectives.
        
        Args:
            query: Original query
            num_queries: Number of queries to generate
            
        Returns:
            List of generated queries from different perspectives
        """
        perspective_prompt = PromptTemplate(
            input_variables=["question", "num_queries"],
            template="""Given the question: "{question}"
            
            Generate {num_queries} different search queries that approach this question from different perspectives:
            - One focused on practical applications
            - One focused on theoretical concepts
            - One focused on examples or case studies
            
            Return only the queries, one per line, without numbering:"""
        )
        
        response = self.llm(perspective_prompt.format(
            question=query, 
            num_queries=num_queries
        ))
        
        queries = [line.strip() for line in response.strip().split('\n') if line.strip()]
        return queries[:num_queries]
    
    def generate_queries_by_specificity(self, query: str) -> List[str]:
        """
        Generate queries with different levels of specificity.
        
        Args:
            query: Original query
            
        Returns:
            List of queries with varying specificity
        """
        specificity_prompt = PromptTemplate(
            input_variables=["question"],
            template="""Given the question: "{question}"
            
            Generate 3 search queries with different levels of specificity:
            1. A more general/broader version of the question
            2. The original question (rephrased)
            3. A more specific/detailed version of the question
            
            Return only the queries, one per line:"""
        )
        
        response = self.llm(specificity_prompt.format(question=query))
        queries = [line.strip() for line in response.strip().split('\n') if line.strip()]
        return queries[:3]
    
    def retrieve_with_fusion(self, query: str, strategy: str = "perspective") -> List[Document]:
        """
        Retrieve documents using query fusion with different strategies.
        
        Args:
            query: Original query
            strategy: Strategy for query generation ("perspective" or "specificity")
            
        Returns:
            Fused results from multiple queries
        """
        if not self.vector_store:
            raise ValueError("Vector store not created.")
            
        # Generate queries based on strategy
        if strategy == "perspective":
            generated_queries = self.generate_queries_by_perspective(query)
        elif strategy == "specificity":
            generated_queries = self.generate_queries_by_specificity(query)
        else:
            raise ValueError("Strategy must be 'perspective' or 'specificity'")
        
        # Add original query
        all_queries = [query] + generated_queries
        
        # Retrieve for each query
        all_results = []
        seen_content = set()
        
        for q in all_queries:
            logger.info(f"Searching for: {q}")
            results = self.vector_store.similarity_search(q, k=3)
            
            for doc in results:
                # Deduplicate based on content
                if doc.page_content not in seen_content:
                    seen_content.add(doc.page_content)
                    all_results.append(doc)
        
        return all_results

# Example Usage
if __name__ == "__main__":
    # Sample documents about machine learning
    ml_documents = [
        "Machine learning is a subset of artificial intelligence that focuses on algorithms that can learn from data.",
        "Supervised learning uses labeled data to train models that can make predictions on new, unseen data.",
        "Unsupervised learning finds patterns in data without labeled examples, such as clustering similar data points.",
        "Deep learning uses neural networks with multiple layers to learn complex patterns in data.",
        "Natural language processing applies machine learning techniques to understand and generate human language.",
        "Computer vision uses machine learning to interpret and understand visual information from images and videos.",
        "Reinforcement learning trains agents to make decisions by rewarding good actions and penalizing bad ones.",
        "Feature engineering is the process of selecting and transforming variables for use in machine learning models.",
        "Cross-validation is a technique used to evaluate machine learning models by testing on different data subsets.",
        "Overfitting occurs when a model learns the training data too well and performs poorly on new data."
    ]
    
    print("=== Multi-Query Retriever Example ===\n")
    
    # Create multi-query retriever
    multi_retriever = CustomMultiQueryRetriever()
    multi_retriever.create_vector_store(ml_documents)
    
    # Test query
    query = "How does ML work?"
    
    print(f"Original Query: {query}")
    
    # Get generated queries
    try:
        generated_queries = multi_retriever.get_generated_queries(query)
        print(f"\nGenerated Queries:")
        for i, q in enumerate(generated_queries, 1):
            print(f"{i}. {q}")
    except Exception as e:
        print(f"Could not generate queries: {e}")
    
    # Retrieve documents
    try:
        results = multi_retriever.retrieve(query)
        print(f"\nRetrieved Documents ({len(results)} found):")
        for i, doc in enumerate(results, 1):
            print(f"{i}. {doc.page_content}")
    except Exception as e:
        print(f"Could not retrieve documents: {e}")
    
    # Advanced multi-query retriever
    print("\n=== Advanced Multi-Query Retriever ===\n")
    
    advanced_retriever = AdvancedMultiQueryRetriever()
    advanced_retriever.create_vector_store(ml_documents)
    
    # Test with different strategies
    query2 = "What is deep learning?"
    
    print(f"Query: {query2}")
    
    # Perspective-based queries
    print("\nPerspective-based queries:")
    try:
        perspective_queries = advanced_retriever.generate_queries_by_perspective(query2)
        for i, q in enumerate(perspective_queries, 1):
            print(f"{i}. {q}")
    except Exception as e:
        print(f"Could not generate perspective queries: {e}")
    
    # Specificity-based queries
    print("\nSpecificity-based queries:")
    try:
        specificity_queries = advanced_retriever.generate_queries_by_specificity(query2)
        for i, q in enumerate(specificity_queries, 1):
            print(f"{i}. {q}")
    except Exception as e:
        print(f"Could not generate specificity queries: {e}")
    
    # Retrieve with fusion
    try:
        fusion_results = advanced_retriever.retrieve_with_fusion(query2, strategy="perspective")
        print(f"\nFusion Results ({len(fusion_results)} found):")
        for i, doc in enumerate(fusion_results, 1):
            print(f"{i}. {doc.page_content}")
    except Exception as e:
        print(f"Could not perform fusion retrieval: {e}")
