# Point to the local JWKS endpoint
jwt.validation.jwks-url=http://localhost:8080/jwks.json

# Use Caffeine cache instead of Redis
jwt.validation.cache-type=CAFFEINE
jwt.validation.cache-expiry=600

# Redis properties (commented out)
# spring.redis.host=trolley.proxy.rlwy.net
# spring.redis.port=27926
# spring.redis.password=wulCCpnHuxpsXSYqSULnvZREAofIvpQW
# jwt.validation.redis-key-prefix=jwks:
